### ISSUE TITLE
MusjidBuddy v1 Roadmap

### ISSUE THREAD

**Issue by electr0de** [DefineX-Studios/MasjidBuddy#1]
MusjidBuddy will be online platform for local masjids to provide services to it's community online. The entire app will include the cross-platform client application for Windows/Web/Android/IOS, and the backend. The technology stack will be React native / Node.js.  This issue represents the breakdown of the first version of the app and act as an EPIC. 
# Breakdown
## Brainstorm.
- [ ] Inquire stakeholders for requirements.
- [ ] Compile the evolving requirements.

## Design.
- [ ] Compile the necessary design documents for application.

## Development.
- [ ]
